# Generated by Django 4.2.26 on 2025-11-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
