# Generated by Django 4.2.26 on 2025-11-11 21:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0003_sharedfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communications", "0003_alter_message_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_topic", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("essay", "Essay"),
                            ("research_paper", "Research Paper"),
                            ("lab_report", "Lab Report"),
                            ("presentation", "Presentation"),
                            ("project", "Project"),
                            ("homework", "Homework"),
                            ("quiz", "Quiz"),
                            ("exam", "Exam"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="student_assignments/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "ppt",
                                    "pptx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("grade_level", models.CharField(blank=True, max_length=50)),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("is_graded", models.BooleanField(default=False)),
                (
                    "grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "Student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "Teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_assignments",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedFileNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_downloaded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="ai_tools.sharedfile",
                    ),
                ),
            ],
            options={
                "db_table": "shared_file_notifications",
                "ordering": ["-created_at"],
                "unique_together": {("shared_file", "recipient")},
            },
        ),
    ]
