# Generated by Django 4.2.26 on 2025-11-14 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_studentenrollmentrequest_family"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communications", "0004_studentassignment_sharedfilenotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("course_request_approved", "Course Request Approved"),
                            ("course_request_declined", "Course Request Declined"),
                            (
                                "course_request_under_review",
                                "Course Request Under Review",
                            ),
                            (
                                "enrollment_request_approved",
                                "Enrollment Request Approved",
                            ),
                            (
                                "enrollment_request_declined",
                                "Enrollment Request Declined",
                            ),
                            (
                                "enrollment_request_under_review",
                                "Enrollment Request Under Review",
                            ),
                            ("new_course_request", "New Course Request"),
                            ("new_enrollment_request", "New Enrollment Request"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_course_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="academics.teachercourserequest",
                    ),
                ),
                (
                    "related_enrollment_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="academics.studentenrollmentrequest",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
