# Generated by Django 4.2.26 on 2025-12-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_studentassignment_authenticity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('course_request_approved', 'Course Request Approved'), ('course_request_declined', 'Course Request Declined'), ('course_request_under_review', 'Course Request Under Review'), ('enrollment_request_approved', 'Enrollment Request Approved'), ('enrollment_request_declined', 'Enrollment Request Declined'), ('enrollment_request_under_review', 'Enrollment Request Under Review'), ('new_course_request', 'New Course Request'), ('new_enrollment_request', 'New Enrollment Request'), ('system_alert', 'System Alert')], max_length=50),
        ),
    ]
