# Generated by Django 4.2.26 on 2025-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='document_type',
            field=models.CharField(choices=[('essay', 'Essay'), ('research_paper', 'Research Paper'), ('lab_report', 'Lab Report'), ('presentation', 'Presentation'), ('project', 'Project'), ('homework', 'Homework'), ('quiz', 'Quiz'), ('exam', 'Exam'), ('group_work', 'Group Work'), ('creative_writing', 'Creative Writing'), ('critical_analysis', 'Critical Analysis'), ('assignment', 'General Assignment'), ('other', 'Other')], max_length=50),
        ),
    ]
