# Generated by Django 5.2.8 on 2025-11-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SmartAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_content", models.TextField()),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("Positive", "Positive"),
                            ("Neutral", "Neutral"),
                            ("Negative", "Negative"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Unknown",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("New", "New"), ("Reviewed", "Reviewed")],
                        default="New",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "smart_alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
