# Generated by Django 4.2.24 on 2025-11-08 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alerts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartalert",
            name="action_taken",
            field=models.TextField(
                blank=True, help_text="Actions taken to address the alert", null=True
            ),
        ),
        migrations.AddField(
            model_name="smartalert",
            name="analysis",
            field=models.TextField(
                blank=True, help_text="AI analysis of the alert", null=True
            ),
        ),
        migrations.AddField(
            model_name="smartalert",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["Admin", "Teacher"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="smartalert",
            name="category",
            field=models.CharField(
                choices=[
                    ("Engagement", "Engagement"),
                    ("Academic", "Academic"),
                    ("Behavioral", "Behavioral"),
                    ("Emotional", "Emotional"),
                    ("Attendance", "Attendance"),
                    ("Other", "Other"),
                ],
                default="Engagement",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="smartalert",
            name="context_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional context data"
            ),
        ),
        migrations.AddField(
            model_name="smartalert",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                default="Medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="smartalert",
            name="recommended_actions",
            field=models.JSONField(
                blank=True, default=list, help_text="List of recommended actions"
            ),
        ),
        migrations.AddField(
            model_name="smartalert",
            name="requires_immediate_attention",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="smartalert",
            name="resolution_notes",
            field=models.TextField(
                blank=True, help_text="Notes on how the alert was resolved", null=True
            ),
        ),
        migrations.AddField(
            model_name="smartalert",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="smartalert",
            name="severity",
            field=models.CharField(
                blank=True, help_text="AI-determined severity", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="smartalert",
            name="source",
            field=models.CharField(
                default="AI Tutor", help_text="Source of the alert", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="smartalert",
            name="suggested_response",
            field=models.TextField(
                blank=True, help_text="Suggested response for teacher", null=True
            ),
        ),
        migrations.AlterField(
            model_name="smartalert",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("In Progress", "In Progress"),
                    ("Reviewed", "Reviewed"),
                    ("Resolved", "Resolved"),
                    ("Dismissed", "Dismissed"),
                ],
                default="New",
                max_length=20,
            ),
        ),
    ]
