# Generated by Django 4.2.26 on 2025-11-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_add_student_feedback'),
        ('alerts', '0003_smartalert_action_taken_smartalert_analysis_and_more'),
    ]

    operations = [
    ]
