# Generated by Django 5.2.8 on 2025-11-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VectorStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="rag_documents/"),
                ),
                ("grade", models.CharField(max_length=50)),
                (
                    "stream",
                    models.CharField(
                        choices=[
                            ("Natural Science", "Natural Science"),
                            ("Social Science", "Social Science"),
                            ("N/A", "N/A"),
                        ],
                        default="N/A",
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Processing", "Processing"),
                            ("Failed", "Failed"),
                        ],
                        default="Processing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rag_vector_stores",
                "ordering": ["-created_at"],
            },
        ),
    ]
