# Generated by Django 4.2.26 on 2025-11-08 05:06

from django.db import migrations, models
import rag.models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vectorstore",
            name="chunk_count",
            field=models.IntegerField(
                default=0, help_text="Number of text chunks in vector store"
            ),
        ),
        migrations.AddField(
            model_name="vectorstore",
            name="vector_store_path",
            field=models.CharField(
                blank=True,
                help_text="Path to ChromaDB vector store",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vectorstore",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=rag.models.vector_store_upload_path
            ),
        ),
    ]
