# Generated by Django 4.2.24 on 2025-11-09 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rag.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rag", "0003_vectorstore_chunk_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamVectorStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("Matric", "Matric Exam"), ("Model", "Model Exam")],
                        help_text="Type of exam (Matric or Model)",
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=rag.models.exam_vector_store_upload_path,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Subject of the exam", max_length=100),
                ),
                (
                    "exam_year",
                    models.CharField(
                        blank=True,
                        help_text="Year of exam (e.g., 2023, 2020-2023, or blank for all years)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        choices=[
                            ("Natural Science", "Natural Science"),
                            ("Social Science", "Social Science"),
                            ("N/A", "N/A"),
                        ],
                        default="N/A",
                        help_text="Academic stream for Grade 12",
                        max_length=50,
                    ),
                ),
                (
                    "chapter",
                    models.CharField(
                        blank=True,
                        help_text="Chapter or topic covered",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Processing", "Processing"),
                            ("Failed", "Failed"),
                        ],
                        default="Processing",
                        max_length=20,
                    ),
                ),
                (
                    "vector_store_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to ChromaDB vector store",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "chunk_count",
                    models.IntegerField(
                        default=0, help_text="Number of text chunks in vector store"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_vector_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rag_exam_vector_stores",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["exam_type", "subject", "exam_year"],
                        name="rag_exam_ve_exam_ty_89e171_idx",
                    ),
                    models.Index(
                        fields=["exam_type", "subject"],
                        name="rag_exam_ve_exam_ty_9493ff_idx",
                    ),
                    models.Index(
                        fields=["status"], name="rag_exam_ve_status_e1b8ba_idx"
                    ),
                ],
            },
        ),
    ]
