# Generated by Django 4.2.26 on 2025-11-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_examvectorstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='examvectorstore',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AddField(
            model_name='vectorstore',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
    ]
