# Generated by Django 4.2.26 on 2025-12-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_examvectorstore_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examvectorstore',
            name='region',
            field=models.CharField(choices=[('Tigray', 'Tigray'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('SNNPR', 'SNNPR'), ('Gambella', 'Gambella'), ('Harari', 'Harari'), ('Sidama', 'Sidama'), ('South West Ethiopia Peoples', 'South West Ethiopia Peoples'), ('Central Ethiopia', 'Central Ethiopia'), ('Addis Ababa', 'Addis Ababa City Administration'), ('Dire Dawa', 'Dire Dawa City Administration')], default='Addis Ababa', max_length=50),
        ),
        migrations.AddField(
            model_name='vectorstore',
            name='region',
            field=models.CharField(choices=[('Tigray', 'Tigray'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('SNNPR', 'SNNPR'), ('Gambella', 'Gambella'), ('Harari', 'Harari'), ('Sidama', 'Sidama'), ('South West Ethiopia Peoples', 'South West Ethiopia Peoples'), ('Central Ethiopia', 'Central Ethiopia'), ('Addis Ababa', 'Addis Ababa City Administration'), ('Dire Dawa', 'Dire Dawa City Administration')], default='Addis Ababa', max_length=50),
        ),
    ]
