# Generated by Django 4.2.26 on 2025-12-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_populate_languages'),
        ('rag', '0006_examvectorstore_region_vectorstore_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='examvectorstore',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.language'),
        ),
        migrations.AddField(
            model_name='vectorstore',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.language'),
        ),
    ]
