# Generated by Django 4.2.26 on 2025-12-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0007_add_language_field'),
    ]

    operations = [
    ]
