# Generated by Django 4.2.26 on 2025-12-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0008_backfill_language_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examvectorstore',
            name='language',
        ),
        migrations.RemoveField(
            model_name='vectorstore',
            name='language',
        ),
    ]
