# Generated by Django 4.2.26 on 2025-11-08 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngagementSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.IntegerField(
                        default=0, help_text="Total session duration in seconds"
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("AI Tutor", "AI Tutor"),
                            ("Practice Labs", "Practice Labs"),
                            ("Reading", "Reading"),
                            ("Assignment", "Assignment"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("total_detections", models.IntegerField(default=0)),
                ("person_detected_count", models.IntegerField(default=0)),
                ("person_detected_percentage", models.FloatField(default=0.0)),
                ("happy_count", models.IntegerField(default=0)),
                ("neutral_count", models.IntegerField(default=0)),
                ("sad_count", models.IntegerField(default=0)),
                ("angry_count", models.IntegerField(default=0)),
                ("fearful_count", models.IntegerField(default=0)),
                ("disgusted_count", models.IntegerField(default=0)),
                ("surprised_count", models.IntegerField(default=0)),
                ("unknown_count", models.IntegerField(default=0)),
                (
                    "dominant_expression",
                    models.CharField(default="unknown", max_length=20),
                ),
                (
                    "attention_required_count",
                    models.IntegerField(
                        default=0, help_text="Count of concerning expressions"
                    ),
                ),
                ("attention_percentage", models.FloatField(default=0.0)),
                ("engagement_score", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "Student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "engagement_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="EngagementSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hour",
                    models.IntegerField(
                        blank=True,
                        help_text="Hour of day (0-23) for hourly summaries",
                        null=True,
                    ),
                ),
                ("total_sessions", models.IntegerField(default=0)),
                ("total_students", models.IntegerField(default=0)),
                ("total_duration_seconds", models.IntegerField(default=0)),
                ("average_duration_seconds", models.IntegerField(default=0)),
                ("happy_percentage", models.FloatField(default=0.0)),
                ("neutral_percentage", models.FloatField(default=0.0)),
                ("sad_percentage", models.FloatField(default=0.0)),
                ("angry_percentage", models.FloatField(default=0.0)),
                ("fearful_percentage", models.FloatField(default=0.0)),
                ("disgusted_percentage", models.FloatField(default=0.0)),
                ("surprised_percentage", models.FloatField(default=0.0)),
                ("unknown_percentage", models.FloatField(default=0.0)),
                ("average_engagement_score", models.FloatField(default=0.0)),
                ("attention_required_percentage", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "engagement_summaries",
                "ordering": ["-date", "-hour"],
                "indexes": [
                    models.Index(fields=["-date"], name="engagement__date_e7f789_idx")
                ],
                "unique_together": {("date", "hour")},
            },
        ),
        migrations.CreateModel(
            name="EngagementSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "expression",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("neutral", "Neutral"),
                            ("sad", "Sad"),
                            ("angry", "Angry"),
                            ("fearful", "Fearful"),
                            ("disgusted", "Disgusted"),
                            ("surprised", "Surprised"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("person_detected", models.BooleanField(default=False)),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="Detection confidence 0-1"
                    ),
                ),
                ("detected_objects", models.JSONField(blank=True, default=list)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="analytics.engagementsession",
                    ),
                ),
            ],
            options={
                "db_table": "engagement_snapshots",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "-timestamp"],
                        name="engagement__session_20d580_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="engagementsession",
            index=models.Index(
                fields=["student", "-started_at"], name="engagement__student_426e34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engagementsession",
            index=models.Index(
                fields=["is_active"], name="engagement__is_acti_40b8cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engagementsession",
            index=models.Index(
                fields=["-started_at"], name="engagement__started_727ce1_idx"
            ),
        ),
    ]
