# Generated by Django 4.2.26 on 2025-11-15 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0005_studentenrollmentrequest_family"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_value", models.CharField(max_length=500)),
                (
                    "model_name",
                    models.CharField(
                        help_text="e.g., gpt-4o, gemini-1.5-flash", max_length=100
                    ),
                ),
                ("max_tokens_per_minute", models.IntegerField(default=90000)),
                ("max_tokens_per_day", models.IntegerField(default=2000000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("rate_limited", "Rate Limited"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("tokens_used_today", models.IntegerField(default=0)),
                ("tokens_used_this_minute", models.IntegerField(default=0)),
                ("last_reset_minute", models.DateTimeField(auto_now_add=True)),
                ("last_reset_day", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_keys_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
            },
        ),
        migrations.CreateModel(
            name="APIKeyProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("gemini", "Google Gemini"),
                            ("serp", "SERP API"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "API Provider",
                "verbose_name_plural": "API Providers",
            },
        ),
        migrations.AlterField(
            model_name="teachercourserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("under_review", "Under Review"),
                    ("course_ended", "Course Ended"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="APIKeyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("used", "Used"),
                            ("deactivated", "Deactivated"),
                            ("reactivated", "Reactivated"),
                            ("created", "Created"),
                            ("deleted", "Deleted"),
                            ("updated", "Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="academics.apikey",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key Log",
                "verbose_name_plural": "API Key Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="apikey",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keys",
                to="academics.apikeyprovider",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apikey",
            unique_together={("provider", "key_value")},
        ),
    ]
