# Generated by Django 4.2.24 on 2025-11-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_studentgrade"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studentgrade",
            new_name="student_gra_student_c37fe3_idx",
            old_name="academics_s_student_idx",
        ),
        migrations.RenameIndex(
            model_name="studentgrade",
            new_name="student_gra_student_37bc7f_idx",
            old_name="academics_s_assignm_idx",
        ),
        migrations.RenameIndex(
            model_name="studentgrade",
            new_name="student_gra_student_6ac58e_idx",
            old_name="academics_s_exam_idx",
        ),
    ]
