# Generated by Django 4.2.24 on 2025-11-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_add_grade_level_stream_to_student_grade"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="studentgrade",
            name="student_gra_student_c37fe3_idx",
        ),
        migrations.AddField(
            model_name="studentgrade",
            name="grade_level",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="studentgrade",
            name="stream",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="studentgrade",
            index=models.Index(
                fields=["student", "subject", "grade_level", "stream"],
                name="student_gra_student_58c44f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentgrade",
            index=models.Index(
                fields=["graded_by", "subject"], name="student_gra_graded__17b4eb_idx"
            ),
        ),
    ]
