# Generated by Django 4.2.24 on 2025-11-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_add_grade_level_stream_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='category',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Exam', 'Exam'), ('Participation', 'Participation'), ('Project', 'Project'), ('Other', 'Other')], default='Other', help_text='Category of the grade for better organization', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]