# Generated by Django 4.2.26 on 2025-11-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_studentgrade_category_studentgrade_grading_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='grade_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
