# Generated by Django 4.2.26 on 2025-11-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_fix_studentgrade_grade_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradeitem",
            name="instructions",
            field=models.TextField(
                blank=True, help_text="Detailed instructions for the assignment"
            ),
        ),
        migrations.AddField(
            model_name="gradeitem",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this grade item is currently active"
            ),
        ),
        migrations.AddField(
            model_name="gradeitem",
            name="release_date",
            field=models.DateTimeField(
                blank=True, help_text="When the assignment becomes available", null=True
            ),
        ),
        migrations.AddField(
            model_name="gradeitem",
            name="rubric",
            field=models.TextField(
                blank=True, help_text="Grading rubric for this item"
            ),
        ),
        migrations.AddField(
            model_name="gradeitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="duration_days",
            field=models.IntegerField(
                blank=True, help_text="Expected duration of unit in days", null=True
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="learning_objectives",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of learning objectives"
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="gradeitem",
            name="weight",
            field=models.FloatField(
                default=1.0, help_text="Weight for weighted grading"
            ),
        ),
        migrations.AddIndex(
            model_name="gradeitem",
            index=models.Index(
                fields=["unit", "due_date"], name="grade_items_unit_id_d81fee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gradeitem",
            index=models.Index(
                fields=["unit", "item_type"], name="grade_items_unit_id_711f4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["course", "order"], name="units_course__7ccb49_idx"
            ),
        ),
    ]
