# Generated by Django 4.2.26 on 2025-11-20 04:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0013_fix_enrollment_unique_constraint'),
    ]

    operations = [
        # No operations - this migration was auto-generated but the model doesn't exist
    ]
