# Generated by Django 4.2.26 on 2025-11-23 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0015_remove_assignmentaction_unique_assignment_teacher_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quiz_type', models.CharField(choices=[('Quiz', 'Quiz'), ('Mid Exam', 'Mid Exam'), ('Final Exam', 'Final Exam')], default='Quiz', max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('grade_level', models.CharField(max_length=10)),
                ('stream', models.CharField(blank=True, max_length=50, null=True)),
                ('chapter', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('duration_minutes', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('is_published', models.BooleanField(default=False)),
                ('allow_retake', models.BooleanField(default=False)),
                ('show_results_immediately', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='academics.course')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'online_quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('work_out', 'Work Out')], max_length=20)),
                ('points', models.FloatField(default=1.0)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for multiple choice')),
                ('correct_answer', models.TextField(help_text='Correct answer text or option index')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer')),
                ('hint', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.onlinequiz')),
            ],
            options={
                'db_table': 'quiz_questions',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='document_type',
            field=models.CharField(choices=[('assignment', 'General Assignment'), ('essay', 'Essay / Written Assignment'), ('exam', 'Examination'), ('project', 'Project / Research Paper'), ('group_work', 'Group Work / Collaboration'), ('lab_report', 'Lab Report'), ('presentation', 'Presentation'), ('homework', 'Homework Assignment'), ('quiz', 'Quiz / Short Answer'), ('creative_writing', 'Creative Writing'), ('critical_analysis', 'Critical Analysis')], default='essay', help_text='Type of document for this assignment', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='assignment_type',
            field=models.CharField(blank=True, choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('homework', 'Homework'), ('project', 'Project'), ('lab_report', 'Lab Report'), ('presentation', 'Presentation'), ('group_work', 'Group Work'), ('essay', 'Essay'), ('critical_analysis', 'Critical Analysis'), ('creative_writing', 'Creative Writing')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('ai_feedback', models.TextField(blank=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='academics.onlinequiz')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_attempts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='academics.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='academics.question')),
            ],
            options={
                'db_table': 'question_responses',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
