# Generated by Django 4.2.26 on 2025-11-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_onlinequiz_question_submission_submitted_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinequiz',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='onlinequiz',
            name='use_rag',
            field=models.BooleanField(default=False, help_text='Whether RAG was used for generation'),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Time limit in seconds for this question', null=True),
        ),
    ]
