# Generated by Django 4.2.26 on 2025-11-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_onlinequiz_difficulty_onlinequiz_use_rag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinequiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Online Quiz', 'verbose_name_plural': 'Online Quizzes'},
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the assignment or quiz', max_length=200, null=True),
        ),
    ]
