# Generated by Django 4.2.26 on 2025-11-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_alter_onlinequiz_options_studentgrade_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='last_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='pause_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
