# Generated by Django 4.2.26 on 2025-11-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_quizattempt_current_question_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('grade_level', models.CharField(max_length=10)),
                ('stream', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_courses',
                'ordering': ['name', 'grade_level'],
                'unique_together': {('name', 'grade_level', 'stream')},
            },
        ),
        migrations.AddField(
            model_name='teachercourserequest',
            name='master_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_requests', to='academics.mastercourse'),
        ),
    ]
