# Generated by Django 4.2.26 on 2025-12-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_mastercourse_teachercourserequest_master_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mastercourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mastercourse',
            name='region',
            field=models.CharField(choices=[('Tigray', 'Tigray'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('SNNPR', 'SNNPR'), ('Gambella', 'Gambella'), ('Harari', 'Harari'), ('Sidama', 'Sidama'), ('South West Ethiopia Peoples', 'South West Ethiopia Peoples'), ('Central Ethiopia', 'Central Ethiopia'), ('Addis Ababa', 'Addis Ababa City Administration'), ('Dire Dawa', 'Dire Dawa City Administration')], default='Addis Ababa', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='mastercourse',
            unique_together={('name', 'grade_level', 'stream', 'region')},
        ),
    ]
