# Generated by Django 4.2.26 on 2025-12-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_alter_mastercourse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mastercourse',
            unique_together={('name', 'grade_level', 'stream', 'region')},
        ),
        migrations.AlterField(
            model_name='mastercourse',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mastercourse',
            unique_together={('name', 'grade_level', 'stream', 'region'), ('code', 'region')},
        ),
    ]
