# Generated by Django 4.2.26 on 2025-12-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_create_language_model'),
    ]

    operations = [
    ]
