# Generated by Django 4.2.26 on 2025-12-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0009_remove_examvectorstore_language_and_more'),
        ('academics', '0026_populate_languages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Amharic', 'Amharic'), ('Afan Oromo', 'Afan Oromo'), ('Tigrigna', 'Tigrigna'), ('Somali', 'Somali')], default='English', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('region', 'grade_level', 'stream', 'subject', 'language')},
        ),
    ]
