# Generated by Django 4.2.26 on 2025-12-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_delete_language_alter_curriculum_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Amharic', 'Amharic'), ('Afan Oromo', 'Afan Oromo'), ('Tigrinya', 'Tigrinya'), ('Somali', 'Somali')], default='English', max_length=50),
        ),
    ]
