# Generated by Django 4.2.26 on 2025-12-06 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0028_alter_curriculum_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinequiz',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Students who have been explicitly valid to take this quiz', limit_choices_to={'role': 'Student'}, related_name='shared_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
