# Generated by Django 4.2.26 on 2025-12-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_onlinequiz_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
