# Generated by Django 4.2.26 on 2025-12-07 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0031_assignmenttype_examtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Students who have been explicitly allowed to view this assignment', limit_choices_to={'role': 'Student'}, related_name='shared_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
