# Generated by Django 4.2.26 on 2025-11-08 23:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedLessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("grade", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=255)),
                (
                    "duration",
                    models.IntegerField(
                        help_text="Duration in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "moe_standard_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "objectives",
                    models.JSONField(
                        default=list, help_text="List of learning objectives"
                    ),
                ),
                (
                    "essential_questions",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "enduring_understandings",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "moe_competencies",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "assessment_plan",
                    models.JSONField(
                        blank=True,
                        help_text="Formative checks, summative task, success criteria",
                        null=True,
                    ),
                ),
                ("materials", models.JSONField(default=list)),
                (
                    "teacher_preparation",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("resource_constraints", models.JSONField(blank=True, null=True)),
                (
                    "five_e_sequence",
                    models.JSONField(
                        blank=True, help_text="5E phases with activities", null=True
                    ),
                ),
                ("activities", models.JSONField(blank=True, default=list, null=True)),
                (
                    "differentiation_strategies",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("homework", models.TextField(blank=True, null=True)),
                ("extensions", models.JSONField(blank=True, default=list, null=True)),
                (
                    "reflection_prompts",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("teacher_notes", models.TextField(blank=True, null=True)),
                ("student_readiness", models.JSONField(blank=True, null=True)),
                ("local_context", models.JSONField(blank=True, null=True)),
                ("rag_enabled", models.BooleanField(default=False)),
                (
                    "curriculum_sources",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this lesson plan is shared publicly with other teachers",
                    ),
                ),
                ("times_used", models.IntegerField(default=0)),
                (
                    "rating",
                    models.FloatField(
                        default=0.0,
                        help_text="Average rating from teachers who used this plan",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("rating_count", models.IntegerField(default=0)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorization",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Teacher who created this lesson plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_lesson_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific teachers this plan is shared with",
                        related_name="shared_lesson_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonPlanRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="ai_tools.savedlessonplan",
                    ),
                ),
                (
                    "rated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plan_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="savedlessonplan",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="ai_tools_sa_created_6f0f7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedlessonplan",
            index=models.Index(
                fields=["grade", "subject"], name="ai_tools_sa_grade_1cc5b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedlessonplan",
            index=models.Index(
                fields=["is_public"], name="ai_tools_sa_is_publ_2f37e1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonplanrating",
            unique_together={("lesson_plan", "rated_by")},
        ),
    ]
