# Generated by Django 4.2.26 on 2025-11-09 01:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_tools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedRubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=255)),
                ("grade_level", models.CharField(max_length=50)),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "rubric_type",
                    models.CharField(
                        choices=[
                            ("analytic", "Analytic Rubric"),
                            ("holistic", "Holistic Rubric"),
                            ("single_point", "Single-Point Rubric"),
                            ("checklist", "Checklist Rubric"),
                        ],
                        default="analytic",
                        help_text="Type of rubric structure",
                        max_length=20,
                    ),
                ),
                (
                    "moe_standard_id",
                    models.CharField(
                        blank=True,
                        help_text="Ethiopian MoE Curriculum Standard ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "learning_objectives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Learning objectives this rubric assesses",
                        null=True,
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=list,
                        help_text="List of assessment criteria with performance levels",
                    ),
                ),
                (
                    "total_points",
                    models.IntegerField(
                        default=100,
                        help_text="Total possible points for this rubric",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "weighting_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether criteria have different weights",
                    ),
                ),
                (
                    "multimodal_assessment",
                    models.BooleanField(
                        default=False,
                        help_text="Whether rubric includes multimodal criteria (visual, audio, etc.)",
                    ),
                ),
                (
                    "alignment_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether criteria alignment with objectives was validated",
                    ),
                ),
                (
                    "alignment_score",
                    models.FloatField(
                        default=0.0,
                        help_text="AI-calculated alignment score (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "performance_levels",
                    models.JSONField(
                        default=list,
                        help_text="Custom performance level labels (e.g., Advanced, Proficient)",
                    ),
                ),
                (
                    "tone_preference",
                    models.CharField(
                        default="professional",
                        help_text="Tone/language preference for descriptions",
                        max_length=50,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this rubric is shared publicly",
                    ),
                ),
                ("times_used", models.IntegerField(default=0)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for organization",
                        null=True,
                    ),
                ),
                (
                    "teacher_notes",
                    models.TextField(
                        blank=True, help_text="Private notes for the teacher", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Teacher who created this rubric",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_rubrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="ai_tools_sa_created_d7b2d7_idx",
                    ),
                    models.Index(
                        fields=["grade_level", "subject"],
                        name="ai_tools_sa_grade_l_73896d_idx",
                    ),
                    models.Index(
                        fields=["rubric_type"], name="ai_tools_sa_rubric__8421a7_idx"
                    ),
                    models.Index(
                        fields=["is_public"], name="ai_tools_sa_is_publ_420eb2_idx"
                    ),
                ],
            },
        ),
    ]
