# Generated by Django 4.2.26 on 2025-11-11 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_tools", "0002_savedrubric"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[("lesson_plan", "Lesson Plan"), ("rubric", "Rubric")],
                        max_length=20,
                    ),
                ),
                ("is_viewed", models.BooleanField(default=False)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message from sender"
                    ),
                ),
                (
                    "lesson_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="ai_tools.savedlessonplan",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="ai_tools.savedrubric",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        help_text="User who shared the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files_shared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        help_text="User who received the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-shared_at"],
                "indexes": [
                    models.Index(
                        fields=["shared_with", "is_viewed"],
                        name="ai_tools_sh_shared__d0618c_idx",
                    ),
                    models.Index(
                        fields=["shared_by", "shared_at"],
                        name="ai_tools_sh_shared__a44030_idx",
                    ),
                ],
            },
        ),
    ]
