# Generated by Django 4.2.26 on 2025-11-12 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_tools", "0003_sharedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_ethiopian_curriculum",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to use Ethiopian curriculum for tutoring",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Selected grade level (e.g., 'Grade 7', 'Grade 11')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        blank=True,
                        help_text="Selected stream for Grades 11-12 (e.g., 'Natural Science', 'Social Science')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Selected subject (e.g., 'Mathematics', 'Physics')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "chapter_input",
                    models.CharField(
                        blank=True,
                        help_text="Chapter/Unit/Lesson input (e.g., 'Chapter 3: Photosynthesis')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "chapter_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Normalized chapter number extracted from chapter_input",
                        null=True,
                    ),
                ),
                (
                    "chapter_title",
                    models.CharField(
                        blank=True,
                        help_text="Extracted chapter title",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "chapter_topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of topics extracted from the chapter content",
                        null=True,
                    ),
                ),
                (
                    "chapter_summary",
                    models.TextField(
                        blank=True,
                        help_text="Brief summary of chapter content for welcome message",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this configuration was used for tutoring",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Student user who owns this configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_configuration",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutor Configuration",
                "verbose_name_plural": "Tutor Configurations",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="ai_tools_tu_user_id_f238f6_idx"
                    ),
                    models.Index(
                        fields=["grade", "subject"], name="ai_tools_tu_grade_98907d_idx"
                    ),
                ],
            },
        ),
    ]
