# Generated by Django 4.2.24 on 2025-11-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0004_tutorconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorconfiguration",
            name="learning_objectives",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Learning objectives extracted from the chapter content",
                null=True,
            ),
        ),
    ]
