# Generated by Django 4.2.26 on 2025-11-21 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_tools', '0005_tutorconfiguration_learning_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='content_type',
            field=models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('rubric', 'Rubric'), ('lesson', 'Lesson')], max_length=20),
        ),
        migrations.CreateModel(
            name='SavedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Full markdown content of the lesson script')),
                ('rag_enabled', models.BooleanField(default=False)),
                ('curriculum_sources', models.JSONField(blank=True, default=list, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(help_text='Teacher who generated this lesson', on_delete=django.db.models.deletion.CASCADE, related_name='created_lessons', to=settings.AUTH_USER_MODEL)),
                ('lesson_plan', models.ForeignKey(blank=True, help_text='Original lesson plan this script was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_lessons', to='ai_tools.savedlessonplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='ai_tools.savedlesson'),
        ),
        migrations.AddIndex(
            model_name='savedlesson',
            index=models.Index(fields=['created_by', '-created_at'], name='ai_tools_sa_created_e302d6_idx'),
        ),
        migrations.AddIndex(
            model_name='savedlesson',
            index=models.Index(fields=['grade', 'subject'], name='ai_tools_sa_grade_7c27cd_idx'),
        ),
    ]
