import React, { useState, useEffect } from 'react';
import {
    BookOpen,
    Sparkles,
    Brain,
    Users,
    TrendingUp,
    Shield,
    Zap,
    CheckCircle,
    ArrowRight,
    GraduationCap,
    Target,
    Award,
    MessageSquare,
    Sun,
    Moon
} from 'lucide-react';

interface LandingPageProps {
    onGetStarted: () => void;
    onLogin: () => void;
}

const LandingPage: React.FC<LandingPageProps> = ({ onGetStarted, onLogin }) => {
    const [theme, setTheme] = useState<'light' | 'dark'>(() => {
        const savedTheme = localStorage.getItem('theme');
        if (savedTheme === 'dark' || savedTheme === 'light') return savedTheme;
        if (typeof window !== 'undefined' && window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
            return 'dark';
        }
        return 'light';
    });

    useEffect(() => {
        if (theme === 'dark') {
            document.documentElement.classList.add('dark');
            localStorage.setItem('theme', 'dark');
        } else {
            document.documentElement.classList.remove('dark');
            localStorage.setItem('theme', 'light');
        }
    }, [theme]);

    const toggleTheme = () => {
        setTheme(prevTheme => (prevTheme === 'light' ? 'dark' : 'light'));
    };

    const features = [
        {
            icon: Brain,
            title: 'AI-Powered Learning',
            description: 'Personalized lessons generated by advanced AI tailored to your learning style and pace.',
            color: 'from-purple-500 to-indigo-600'
        },
        {
            icon: Users,
            title: 'Interactive Classroom',
            description: 'Engage with virtual whiteboards, real-time chat, and collaborative learning tools.',
            color: 'from-blue-500 to-cyan-600'
        },
        {
            icon: TrendingUp,
            title: 'Track Progress',
            description: 'Monitor your learning journey with XP, levels, streaks, and detailed analytics.',
            color: 'from-green-500 to-emerald-600'
        },
        {
            icon: Shield,
            title: 'Safe & Secure',
            description: 'Enterprise-grade security with role-based access control for students, teachers, and parents.',
            color: 'from-orange-500 to-amber-600'
        },
        {
            icon: Sparkles,
            title: 'AI Teaching Assistants',
            description: 'Automated lesson creation, grading, feedback generation, and content detection.',
            color: 'from-pink-500 to-rose-600'
        },
        {
            icon: Target,
            title: 'Standards-Aligned',
            description: 'Curriculum-aligned content that meets educational standards and learning objectives.',
            color: 'from-teal-500 to-cyan-600'
        }
    ];

    const benefits = [
        'Create engaging lessons in seconds',
        'Real-time student engagement monitoring',
        'Automated grading with rubrics',
        'Plagiarism and AI content detection',
        'Comprehensive analytics dashboard',
        'Multi-role support (Students, Teachers, Parents, Admins)'
    ];

    const stats = [
        { value: '10K+', label: 'Active Users' },
        { value: '50K+', label: 'Lessons Created' },
        { value: '95%', label: 'Satisfaction Rate' },
        { value: '24/7', label: 'AI Support' }
    ];

    return (
        <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-indigo-50 dark:from-gray-900 dark:via-gray-800 dark:to-indigo-900">
            {/* Theme Toggle Button - Fixed Position */}
            <button
                onClick={toggleTheme}
                className="fixed top-6 right-6 z-50 p-3 rounded-full bg-white dark:bg-gray-800 text-gray-800 dark:text-gray-200 shadow-lg hover:shadow-xl border-2 border-gray-200 dark:border-gray-700 transition-all duration-200 hover:scale-110"
                aria-label="Toggle theme"
            >
                {theme === 'light' ? <Moon className="h-6 w-6" /> : <Sun className="h-6 w-6" />}
            </button>

            {/* Hero Section */}
            <section className="relative overflow-hidden">
                {/* Background Decoration */}
                <div className="absolute inset-0 overflow-hidden">
                    <div className="absolute -top-40 -right-40 w-80 h-80 bg-purple-300 dark:bg-purple-600 rounded-full mix-blend-multiply dark:mix-blend-soft-light filter blur-xl opacity-30 animate-blob"></div>
                    <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-indigo-300 dark:bg-indigo-600 rounded-full mix-blend-multiply dark:mix-blend-soft-light filter blur-xl opacity-30 animate-blob animation-delay-2000"></div>
                    <div className="absolute top-40 left-40 w-80 h-80 bg-pink-300 dark:bg-pink-600 rounded-full mix-blend-multiply dark:mix-blend-soft-light filter blur-xl opacity-30 animate-blob animation-delay-4000"></div>
                </div>

                <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-24">
                    <div className="text-center">
                        {/* Logo and Brand */}
                        <div className="flex items-center justify-center space-x-3 mb-8">
                            <div className="w-16 h-16 bg-gradient-to-br from-indigo-600 to-purple-600 rounded-2xl flex items-center justify-center shadow-lg">
                                <BookOpen size={32} className="text-white" />
                            </div>
                            <h1 className="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white">
                                AI Virtual Classroom
                            </h1>
                        </div>

                        {/* Tagline */}
                        <h2 className="text-3xl md:text-5xl lg:text-6xl font-extrabold text-gray-900 dark:text-white mb-6 leading-tight">
                            Transform Education with
                            <span className="block text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-purple-600 dark:from-indigo-400 dark:to-purple-400">
                                AI-Powered Learning
                            </span>
                        </h2>

                        <p className="text-xl md:text-2xl text-gray-600 dark:text-gray-300 mb-12 max-w-3xl mx-auto">
                            Experience the future of education with personalized AI tutoring, interactive classrooms, 
                            and intelligent teaching assistants.
                        </p>

                        {/* CTA Buttons */}
                        <div className="flex flex-col sm:flex-row items-center justify-center space-y-4 sm:space-y-0 sm:space-x-6 mb-12">
                            <button
                                onClick={onGetStarted}
                                className="group px-8 py-4 bg-gradient-to-r from-indigo-600 to-purple-600 text-white text-lg font-semibold rounded-xl shadow-lg hover:shadow-xl transform hover:scale-105 transition-all duration-200 flex items-center space-x-2"
                            >
                                <span>Get Started Free</span>
                                <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" />
                            </button>
                            <button
                                onClick={onLogin}
                                className="px-8 py-4 bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-lg font-semibold rounded-xl shadow-md hover:shadow-lg border-2 border-gray-200 dark:border-gray-700 transform hover:scale-105 transition-all duration-200"
                            >
                                Sign In
                            </button>
                        </div>

                        {/* Trust Indicators */}
                        <div className="flex flex-wrap items-center justify-center space-x-8 text-sm text-gray-500 dark:text-gray-400">
                            <div className="flex items-center space-x-2">
                                <CheckCircle size={16} className="text-green-500" />
                                <span>No credit card required</span>
                            </div>
                            <div className="flex items-center space-x-2">
                                <CheckCircle size={16} className="text-green-500" />
                                <span>Free for students</span>
                            </div>
                            <div className="flex items-center space-x-2">
                                <CheckCircle size={16} className="text-green-500" />
                                <span>GDPR compliant</span>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* Stats Section */}
            <section className="py-12 bg-white/50 dark:bg-gray-800/50 backdrop-blur-sm">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
                        {stats.map((stat, index) => (
                            <div key={index} className="text-center">
                                <div className="text-4xl md:text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-purple-600 dark:from-indigo-400 dark:to-purple-400 mb-2">
                                    {stat.value}
                                </div>
                                <div className="text-gray-600 dark:text-gray-400 font-medium">
                                    {stat.label}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Features Section */}
            <section className="py-20">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="text-center mb-16">
                        <h2 className="text-3xl md:text-4xl font-bold text-gray-900 dark:text-white mb-4">
                            Powerful Features for Modern Education
                        </h2>
                        <p className="text-xl text-gray-600 dark:text-gray-300 max-w-2xl mx-auto">
                            Everything you need to create, manage, and deliver exceptional learning experiences.
                        </p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {features.map((feature, index) => {
                            const Icon = feature.icon;
                            return (
                                <div
                                    key={index}
                                    className="group bg-white dark:bg-gray-800 rounded-2xl p-8 shadow-md hover:shadow-xl transition-all duration-300 border border-gray-200 dark:border-gray-700 hover:border-indigo-500 dark:hover:border-indigo-500"
                                >
                                    <div className={`w-14 h-14 rounded-xl bg-gradient-to-br ${feature.color} flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-300`}>
                                        <Icon size={28} className="text-white" />
                                    </div>
                                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3">
                                        {feature.title}
                                    </h3>
                                    <p className="text-gray-600 dark:text-gray-400">
                                        {feature.description}
                                    </p>
                                </div>
                            );
                        })}
                    </div>
                </div>
            </section>

            {/* Benefits Section */}
            <section className="py-20 bg-gradient-to-br from-indigo-600 to-purple-600 dark:from-indigo-700 dark:to-purple-700">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
                        <div>
                            <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
                                Why Choose AI Virtual Classroom?
                            </h2>
                            <p className="text-xl text-indigo-100 mb-8">
                                Join thousands of educators and students who are already experiencing the future of education.
                            </p>
                            <div className="space-y-4">
                                {benefits.map((benefit, index) => (
                                    <div key={index} className="flex items-start space-x-3">
                                        <CheckCircle size={24} className="text-green-300 flex-shrink-0 mt-1" />
                                        <span className="text-lg text-white">{benefit}</span>
                                    </div>
                                ))}
                            </div>
                        </div>
                        <div className="relative">
                            <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-8 border border-white/20">
                                <div className="space-y-6">
                                    <div className="flex items-center space-x-4">
                                        <div className="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center">
                                            <GraduationCap size={24} className="text-white" />
                                        </div>
                                        <div>
                                            <div className="text-white font-semibold">For Students</div>
                                            <div className="text-indigo-200 text-sm">Personalized learning paths</div>
                                        </div>
                                    </div>
                                    <div className="flex items-center space-x-4">
                                        <div className="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center">
                                            <Award size={24} className="text-white" />
                                        </div>
                                        <div>
                                            <div className="text-white font-semibold">For Teachers</div>
                                            <div className="text-indigo-200 text-sm">Automated grading & feedback</div>
                                        </div>
                                    </div>
                                    <div className="flex items-center space-x-4">
                                        <div className="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center">
                                            <MessageSquare size={24} className="text-white" />
                                        </div>
                                        <div>
                                            <div className="text-white font-semibold">For Parents</div>
                                            <div className="text-indigo-200 text-sm">Real-time progress tracking</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* CTA Section */}
            <section className="py-20">
                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
                    <h2 className="text-3xl md:text-4xl font-bold text-gray-900 dark:text-white mb-6">
                        Ready to Transform Your Learning Experience?
                    </h2>
                    <p className="text-xl text-gray-600 dark:text-gray-300 mb-8">
                        Join our community and start your journey with AI-powered education today.
                    </p>
                    <button
                        onClick={onGetStarted}
                        className="group px-10 py-5 bg-gradient-to-r from-indigo-600 to-purple-600 text-white text-xl font-semibold rounded-xl shadow-lg hover:shadow-xl transform hover:scale-105 transition-all duration-200 flex items-center space-x-3 mx-auto"
                    >
                        <Zap size={24} />
                        <span>Start Learning Now</span>
                        <ArrowRight size={24} className="group-hover:translate-x-1 transition-transform" />
                    </button>
                </div>
            </section>

            {/* Footer */}
            <footer className="py-12 bg-gray-900 dark:bg-black text-gray-400">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="flex flex-col md:flex-row items-center justify-between">
                        <div className="flex items-center space-x-2 mb-4 md:mb-0">
                            <BookOpen size={24} className="text-indigo-400" />
                            <span className="text-white font-semibold">AI Virtual Classroom</span>
                        </div>
                        <div className="text-sm">
                            © 2025 AI Virtual Classroom. All rights reserved.
                        </div>
                    </div>
                </div>
            </footer>

            <style>{`
                @keyframes blob {
                    0%, 100% { transform: translate(0, 0) scale(1); }
                    25% { transform: translate(20px, -50px) scale(1.1); }
                    50% { transform: translate(-20px, 20px) scale(0.9); }
                    75% { transform: translate(50px, 50px) scale(1.05); }
                }
                .animate-blob {
                    animation: blob 7s infinite;
                }
                .animation-delay-2000 {
                    animation-delay: 2s;
                }
                .animation-delay-4000 {
                    animation-delay: 4s;
                }
            `}</style>
        </div>
    );
};

export default LandingPage;
