# Generated by Django 4.2.26 on 2025-12-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_family_familymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending Review', 'Pending Review'), ('Active', 'Active'), ('Rejected', 'Rejected'), ('Suspended', 'Suspended')], default='Incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='teacher_cvs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('Tigray', 'Tigray'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('SNNPR', 'SNNPR'), ('Gambella', 'Gambella'), ('Harari', 'Harari'), ('Sidama', 'Sidama'), ('South West Ethiopia Peoples', 'South West Ethiopia Peoples'), ('Central Ethiopia', 'Central Ethiopia'), ('Addis Ababa', 'Addis Ababa City Administration'), ('Dire Dawa', 'Dire Dawa City Administration')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_identification_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade_level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
