# Generated by Django 4.2.26 on 2025-12-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number with country code, e.g., +251911223344', max_length=15, null=True),
        ),
    ]
