# Generated by Django 4.2.26 on 2025-12-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stream',
            field=models.CharField(blank=True, choices=[('Natural', 'Natural Science'), ('Social', 'Social Science')], max_length=20, null=True),
        ),
    ]
