# Generated by Django 4.2.26 on 2025-12-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='+251000000000', help_text='Mobile number with country code, e.g., +251911223344', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('Tigray', 'Tigray'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('SNNPR', 'SNNPR'), ('Gambella', 'Gambella'), ('Harari', 'Harari'), ('Sidama', 'Sidama'), ('South West Ethiopia Peoples', 'South West Ethiopia Peoples'), ('Central Ethiopia', 'Central Ethiopia'), ('Addis Ababa', 'Addis Ababa City Administration'), ('Dire Dawa', 'Dire Dawa City Administration')], default='Addis Ababa', max_length=50),
        ),
    ]
